### ISSUE TITLE
CT: Tandem was required but not supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/arithmetic#186]
```
arithmetic : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/tandem/js/Tandem.js?bust=1537551110011:101:21)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/tandem/js/PhetioObject.js?bust=1537551110011:151:19)
    at BooleanProperty.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/tandem/js/PhetioObject.js?bust=1537551110011:80:12)
    at BooleanProperty.Property [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/axon/js/Property.js?bust=1537551110011:84:18)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/axon/js/BooleanProperty.js?bust=1537551110011:38:14)
    at PushButtonModel.ButtonModel [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/sun/js/buttons/ButtonModel.js?bust=1537551110011:49:28)
    at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/sun/js/buttons/PushButtonModel.js?bust=1537551110011:44:17)
    at LevelSelectionButton.RectangularPushButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/sun/js/buttons/RectangularPushButton.js?bust=1537551110011:41:24)
    at new LevelSelectionButton (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/vegas/js/LevelSelectionButton.js?bust=1537551110011:119:27)
Approximately 9/21/2018, 11:13:16 AM
arithmetic : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/tandem/js/Tandem.js?bust=1537551110011:101:21)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/tandem/js/PhetioObject.js?bust=1537551110011:151:19)
    at BooleanProperty.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/tandem/js/PhetioObject.js?bust=1537551110011:80:12)
    at BooleanProperty.Property [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/axon/js/Property.js?bust=1537551110011:84:18)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/axon/js/BooleanProperty.js?bust=1537551110011:38:14)
    at PushButtonModel.ButtonModel [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/sun/js/buttons/ButtonModel.js?bust=1537551110011:49:28)
    at new PushButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/sun/js/buttons/PushButtonModel.js?bust=1537551110011:44:17)
    at LevelSelectionButton.RectangularPushButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/sun/js/buttons/RectangularPushButton.js?bust=1537551110011:41:24)
    at new LevelSelectionButton (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/vegas/js/LevelSelectionButton.js?bust=1537551110011:119:27)
Approximately 9/21/2018, 11:13:16 AM
arithmetic : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)

SimTests: arithmetic: iframe api failed:
instance metadata should match for arithmetic.requiredTandem
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/js/tests/SimTests.js?bust=1537550678761:272:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:285:81)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1537549996577/phet-io-wrappers/common/js/Client.js:322:13)


Approximately 9/21/2018, 11:13:16 AM
```

**Comment by zepumph** [comment]
Thanks @KatieWoe. @samreid added this sim to the phet-io list yesterday, so now it is getting phet-io testing although it doesn't have anywhere near completed instrumentation. @samreid what do you recommend?
